# # General configs
source = $HOME/.config/hypr/hyprland/execs.conf
source = $HOME/.config/hypr/hyprland/colors.conf
source = $HOME/.config/hypr/hyprland/env.conf
source = $HOME/.config/hypr/hyprland/default.conf
source = $HOME/.config/hypr/hyprland/general.conf
source = $HOME/.config/hypr/hyprland/keybinds.conf
source = $HOME/.config/hypr/hyprland/rules.conf

# # User specific configs
source = $HOME/.config/hypr/custom/execs.conf
source = $HOME/.config/hypr/custom/default.conf
source = $HOME/.config/hypr/custom/general.conf
source = $HOME/.config/hypr/custom/keybinds.conf
source = $HOME/.config/hypr/custom/rules.conf

