$color_base = 15,17,23 # #0f1117
$color_mantle = 20,24,35 # #141823 
$color_surface = 27,33,48 # #1b2130
$color_overlay = 36,44,63 # #242c3f
# text
$text_primary = 230,233,242 # #e6e9f2
$text_primary_dark = 183,192,216 # #b7c0d8
$text_primary_darken = 140,149,170 # #8c95aa

#  accents
$accent_purple = 167,139,250 # #a78bfa
$accent_purple_light = 203,166,247 # #cba6f7
$accent_rose =  232,162,182 # #e8a2b6
$accent_peach_light = 242,205,205 # #f2cdcd
$accent_blue_light = 137,180,250 # #89b4fa

# functional 
$color_success = #94e2d5
$color_warning = #f9e2af
$color_error = #f38ba8
$color_info = #74c7ec
