$terminal = kitty
$filemanager = nautilus
# configs related to menu is configured based on **Fuzzel** changing it can break a few stuff
$menu = fuzzel
$powermanager = wlogout
$browser = google-chrome-stable
