###################
### KEYBINDINGS ###
###################
$SCRIPTSDIR = ~/.config/hypr/scripts/
$SSDIR = ~/Pictures/Screenshot
$mainMod = SUPER 

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

# Default apps
bind = $mainMod, T, exec, $terminal
bind = CONTROL_ALT, DELETE, exec, $powermanager
bind = $mainMod, W, exec, $browser
bind = $mainMod, E, exec, $filemanager



# App launch
bind = $mainMod, Z, exec, zen-browser
bind = CTRL $mainMod, V, exec, pavucontrol
bind = $mainMod, C, exec, code

# Screenshot
bind = $mainMod Shift, S, exec, grimblast -n copysave area 
bindl=,Print,exec, grimblast --freeze --notify copy 

# App Launcher, Clipboard, Emoji
# bind = $mainMod, space, exec, rofi -show drun
bind = $mainMod, space, exec, $menu
bind = $mainMod, V, exec, $SCRIPTSDIR/clipmenu.sh
bind = SUPER, period, exec, hypremoji

bind = $mainMod, F, fullscreen
bind = $mainMod, Q, killactive
bind = $mainMod Shift, Q, forcekillactive
bind = ALT, F, togglefloating

# Workspace navigation
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = $mainMod, mouse_down, workspace, -1
bind = $mainMod, mouse_up, workspace, +1
bind = $mainMod Shift, mouse_up, movetoworkspace, +1
bind = $mainMod Shift, mouse_down, movetoworkspace, -1
bind = $mainMod, page_up, workspace, -1
bind = $mainMod, page_down, workspace, +1
bind = $mainMod Shift, page_up, movetoworkspace, -1
bind = $mainMod Shift, page_down, movetoworkspace, +1
bind = $mainMod Shift, right, movetoworkspace, +1
bind = $mainMod Shift, left, movetoworkspace, -1
bind = Ctrl + $mainMod, mouse_up, workspace,r+1
bind = Ctrl + $mainMod, mouse_down, workspace,r-1

bind = ALT, tab, cyclenext

bind = $mainMod, Right, movewindow, r
bind = $mainMod, left, movewindow, l
bind = $mainMod, up, movewindow, t
bind = $mainMod, down, movewindow, b

bindm = $mainMod, mouse:272, movewindow      # ALT + LMB: Move a window by dragging more than 10px.
bindc = $mainMod, mouse:272, togglefloating  # ALT + LMB: Floats a window by clicking
bindm = $mainMod, mouse:273, resize 1


# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# test
bind = Super Alt, f12, exec, notify-send "Hyprland Version: $(hyprctl version | head -2 | tail -1 | cut-f2 -d ' ')" "owo" -a 'hyprland keybind'
